import { getHomepageData, getAllPages } from "../../lib/store";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

export async function GET(req) {
  try {
    const host = req.headers.get("host") || "www.18homes.in";
    const protocol = host.includes("localhost") ? "http" : "https";
    const baseUrl = `${protocol}://${host}`;

    // Get all published pages from the database
    const allPages = await getAllPages();
    const publishedPages = allPages.filter((p) => p.status === "published");

    // Maintain unique sitemap pages using a Map
    const sitemapItems = new Map();

    const defaultStatic = [
      { path: "", title: "Buy, Sell & Rent Properties Online | Real Estate Deals Near You" },
      { path: "buy", title: "18 Homes - Best Property for Sale and Rent in NCR" },
      { path: "sell", title: "18 Homes - Best Property for Sale and Rent in NCR" },
      { path: "contact", title: "18 Homes - Best Property for Sale and Rent in NCR" },
      { path: "login-signup", title: "18 Homes - Best Property for Sale and Rent in NCR" },
      { path: "about", title: "18 Homes - Best Property for Sale and Rent in NCR" },
    ];

    for (const item of defaultStatic) {
      sitemapItems.set(item.path, {
        url: `${baseUrl}/${item.path}`.replace(/\/$/, ""),
        title: item.title,
      });
    }

    for (const page of publishedPages) {
      const cleanSlug = String(page.slug || "").replace(/^\/+|\/+$/g, "");
      const pageUrl = `${baseUrl}/${cleanSlug}`;
      const pageTitle = page.title || "18 Homes - Best Property for Sale and Rent in NCR";

      // If a dynamic page matches a static path, overwrite or use page title
      sitemapItems.set(cleanSlug, {
        url: pageUrl,
        title: pageTitle,
      });
    }

    const itemsArray = Array.from(sitemapItems.values());
    const totalPages = itemsArray.length;
    const lastUpdatedDate = new Date().toLocaleDateString("en-US", {
      year: "numeric",
      month: "long",
      day: "numeric",
    });

    let listItemsHtml = "";
    itemsArray.forEach((item, index) => {
      const isLast = index === totalPages - 1;
      const classAttr = isLast ? 'class="lpage last-page"' : 'class="lpage"';
      listItemsHtml += `<li ${classAttr}><a href="${item.url}" title="${item.title}">${item.title}</a></li>\n`;
    });

    const html = `<!doctype html>
<html lang="en">

<head>
	<meta charset="utf-8" />
	<title>18homes.in Site Map</title>
	<meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" name="viewport" />
	<style type="text/css">
	body {
		background-color: #fff;
		font-family: "Roboto", "Helvetica", "Arial", sans-serif;
		margin: 0;
	}

	#top {
		background-color: #b1d1e8;
		font-size: 16px;
		padding-bottom: 40px;
	}

	nav {
		font-size: 24px;
		margin: 0px 30px 0px;
		border-bottom-left-radius: 6px;
		border-bottom-right-radius: 6px;
		background-color: #f3f3f3;
		color: #666;
		box-shadow: 0 10px 20px -12px rgba(0, 0, 0, 0.42), 0 3px 20px 0px rgba(0, 0, 0, 0.12), 0 8px 10px -5px rgba(0, 0, 0, 0.2);
		padding: 10px 0;
		text-align: center;
		z-index: 1;
	}

	h3 {
		margin: auto;
		padding: 10px;
		max-width: 600px;
		color: #666;
	}

	h3 span {
		float: right;
	}

	h3 a {
		font-weight: normal;
		display: block;
	}

	#cont {
		position: relative;
		border-radius: 6px;
		box-shadow: 0 16px 24px 2px rgba(0, 0, 0, 0.14), 0 6px 30px 5px rgba(0, 0, 0, 0.12), 0 8px 10px -5px rgba(0, 0, 0, 0.2);
		background: #f3f3f3;
		margin: -20px 30px 0px 30px;
		padding: 20px;
	}

	a:link,
	a:visited {
		color: #0180AF;
		text-decoration: underline;
	}

	a:hover {
		color: #666;
	}

	#footer {
		padding: 10px;
		text-align: center;
	}

	ul {
    	margin: 0px;
    	padding: 0px;
    	list-style: none;
	}
	li {
		margin: 0px;
	}
	li ul {
		margin-left: 20px;
	}

	.lhead {
		background: #ddd;
		padding: 10px;
    	margin: 10px 0px;
	}

	.lcount {
		padding: 0px 10px;
	}

	.lpage {
		border-bottom: #ddd 1px solid;
		padding: 5px;
	}
	.last-page {
		border: none;
	}
	</style>
</head>

<body>
	<div id="top">
		<nav>18homes.in HTML Site Map</nav>
		<h3>
<span>Last updated: ${lastUpdatedDate}<br />
Total pages: ${totalPages}</span>
<a href="${baseUrl}">18homes.in Homepage</a>
</h3></div>
	<div id="cont">
		<ul class="level-0">
            <li class="lhead">${baseUrl}/  <span class="lcount">${totalPages} pages</span></li>
            <li><ul class="level-1">
				${listItemsHtml}
			</ul></li>
		</ul>
	</div>
	<div id="footer">
		Page dynamically generated by 18homes.in sitemap generator
	</div>
</body>

</html>`;

    return new Response(html, {
      status: 200,
      headers: {
        "Content-Type": "text/html; charset=utf-8",
        "Cache-Control": "public, s-maxage=3600, stale-while-revalidate=59",
      },
    });
  } catch (error) {
    console.error("[GET /sitemap.html]", error);
    return new Response("Error generating HTML sitemap", { status: 500 });
  }
}
